services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: always
    network_mode: "host"
    env_file:
      - .env
    expose:
      - "25"
      - "8080"
      - "4443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    volumes:
      - /mnt/mail:/data