services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: always
    # network_mode: "host"
    env_file:
      - .env
    ports:
      - "25:25"
      - "8080:8080"
      - "4443:4443"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "995"
    volumes:
      - /mnt/mail:/data
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true